---
title: "Untitled"
format: revealjs
server: shiny
---
```{r}
library(shiny)
library(plotly)
library(bslib)
```

## About me

##  The basics

## The basics - 

```{r}
fluidRow(
    plotOutput(
        "scatter_plot",
        height = 350,
        click = clickOpts(id = "plot_click"),
        dblclick = dblclickOpts(id = "plot_dblclick"),
        hover = hoverOpts(id = "plot_hover"),
        brush = brushOpts(id = "plot_brush"),
    ),
    layout_columns(
        col_widths = c(4, 4, 4, 4),
        card(
            verbatimTextOutput("click_info")
        ),
        card(
            verbatimTextOutput("dblclick_info")
        ),
        card(
            verbatimTextOutput("hover_info")
        ),
        card(
            verbatimTextOutput("brush_info")
        )
    )
)
```

```{r}
#| context: server
output$scatter_plot <- renderPlot({
    plot(mtcars$wt, mtcars$mpg)
})

output$click_info <- renderPrint({
    cat("input$plot_click:\n")
    str(input$plot_click)
})
output$hover_info <- renderPrint({
    cat("input$plot_hover:\n")
    str(input$plot_hover)
})
output$dblclick_info <- renderPrint({
    cat("input$plot_dblclick:\n")
    str(input$plot_dblclick)
})
output$brush_info <- renderPrint({
    cat("input$plot_brush:\n")
    str(input$plot_brush)
})
```

## Facet plot

## Brushes

